# DATASET KOMENTAR YOUTUBE

## Install & Import Library

In [149]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import html
import warnings
warnings.filterwarnings('ignore')

In [150]:
import zipfile
import pandas as pd

# Ekstrak ZIP dulu
with zipfile.ZipFile("SENTIMENT 3 VIDEO YOUTUBE.zip", "r") as z:
    z.extractall("yt_extracted")

# Lalu baca file CSV yang ada di dalamnya
df_yt = pd.read_csv("yt_extracted/SENTIMENT 3 VIDEO YOUTUBE/DATA_KOMEN_FULL_3_VIDEO.csv")
df_gd = pd.read_csv("data_gadgetin_6000.csv")

In [151]:
df_yt.head(20)

,Channel_Sumber,Username,Komentar,Like_Count,Tanggal,Tipe_Komentar
0,Jagat Review,@CheverrlynAdyba,"Untuk link pembelian chamon 40 pro 5g kok gk ada bang,",0,2026-03-21T13:04:52Z,Utama
1,Jagat Review,@caesarrizkie9742,"Ngomongin Rog kah ?, kameranya makin menurun, soalnya saya jg dulu liat revi...",0,2026-03-17T20:41:02Z,Utama
2,Jagat Review,@adealfian664,Sebagai user Samsung. One UI itu UI paling enak. UI yang &quot;apa lu mau gu...,0,2026-03-13T23:27:54Z,Utama
3,Jagat Review,@RsyatLyioz,"Tecno pova 7 ultra 5g ,bg",0,2026-03-12T20:11:30Z,Utama
4,Jagat Review,@CitraUtut,bang tolong buatin dong rekomendasi buat lebaran 2026,2,2026-03-02T23:12:23Z,Utama
5,Jagat Review,@KellenArgos-q1f9m,"Gue dapet Infinix gt30 pro 12/512 di harga 3,7 juta, baru tau dari sini kala...",0,2026-03-01T00:48:32Z,Utama
6,Jagat Review,@rifqifadilla6877,Beli toko apa bg,0,2026-03-02T16:50:28Z,Reply
7,Jagat Review,@RahmatRamadhan-e6k,Kalo Samsung s24fe5g aman kh beli taun 2026,0,2026-02-28T15:16:53Z,Utama
8,Jagat Review,@mailnasrunyuiik4983,"bingung gua di seri 3-5 juta ini pada bagus bagus, gua mau beli hp buat leba...",0,2026-02-28T06:41:12Z,Utama
9,Jagat Review,@dengamil2908,kalo camera mending camon tapi kalo untuk ke game mending gt,0,2026-02-28T09:12:22Z,Reply
10,Jagat Review,@RDWNSahabat-Quran,"Bahas samsung galaxy seri M, Gak kalah mantap, gw user M34 dh 2 tahun lebih,...",0,2026-02-26T01:00:12Z,Utama
11,Jagat Review,@rarabatara,"Redmi note 15 5G, ultrawide termurah dengan chipset 5G",0,2026-02-22T02:54:42Z,Utama
12,Jagat Review,@RallyFury-i5k5p,Nah. Kalo dari segi kamera saja. Foto video. Lebih menang Samsung a26 apa a3...,0,2026-02-21T17:13:30Z,Utama
13,Jagat Review,@KatalisOpsianal,Lah hp gw lemot tapi panas gimana tuh😂😂😂 waktunya ganti kali ya udah 5th pak...,0,2026-02-20T20:51:25Z,Utama
14,Jagat Review,@mandra213,kira2 moto g57/67 power bisa masuk ga ya? atau emg ga terpilih aja? wkwk,0,2026-02-17T02:28:54Z,Utama
15,Jagat Review,@zall1150,"<a href=""https://www.youtube.com/watch?v=YuU7NopgJXY&amp;t=793"">13:13</a> r...",0,2026-02-16T01:09:48Z,Utama
16,Jagat Review,@alwafaathea,Di masa depan mending lebih pentingin buat kembangin pendingin mesin dah sup...,1,2026-02-14T08:35:46Z,Utama
17,Jagat Review,@God.SP3ed,"Om Ded, Om Chris dan warga JR semua, info dong dari hp yg disebutkan disini ...",0,2026-02-10T00:57:53Z,Utama
18,Jagat Review,@elvanwijaya3501,"<a href=""https://www.youtube.com/watch?v=YuU7NopgJXY&amp;t=700"">11:40</a> po...",0,2026-02-09T17:03:43Z,Utama
19,Jagat Review,@SuperRossonere,iqoo Z10 pake layar P Oled atau amoled sih???,0,2026-02-07T16:43:22Z,Utama

In [152]:
df_gd.head(20)

,Author,Comment,Likes,Time
0,@reykef,thankyou bang,0,2026-03-04T00:10:40Z
1,@margaemas25,Lg pada naik ya hp?,0,2026-03-03T02:14:55Z
2,@sofianiwirawan5918,Bang rekomen hp 2jt up dikit plis,0,2026-03-03T01:43:16Z
3,@atiqmamu0366,Ga buat rekomendasi hp buat lebaran bang?😅,0,2026-03-02T22:24:11Z
4,@cicaksudahberani,srriusss g99 samsung 1.5jt????,0,2026-03-02T14:42:34Z
5,@Issqois,Bg edisi lebaran kapan nih,2,2026-03-02T08:24:31Z
6,@vidtugass,Infinix hot 60 pro buat pemakaian jangka panjang min 4 tahun worth gak beli ...,0,2026-03-01T08:06:18Z
7,@Eris-t8j,Pilihan gw emang tepat beli Infinix hot 50 4g buat main genshin lumayan.,0,2026-02-28T19:31:40Z
8,@dawntv3216,Ditunggu review lebaran 2026 bang,0,2026-02-28T17:40:05Z
9,@aahumairah5293,Rekomendasi hp 3jtan desain kecil spek mantap bang,0,2026-02-28T12:12:28Z
10,@MysteryMystery-k5l,Bismillah semoga aku bisa beli hp di tahun 2026 ini.Mohon doain,0,2026-02-28T04:06:41Z
11,@Dyyput.,Mending techno comon apa Infinix note 60 ya,0,2026-02-27T14:23:26Z
12,@NoviYuhaeni,Yg udh pake tecno camon ketahanan nya gimana? Awet gaa bantu jawab plisss,0,2026-02-27T08:48:17Z
13,@AnggaRiskiandi,bikin lagi bang yg rekomendasi,0,2026-02-27T04:39:46Z
14,@FreeFire-ji9cs,Link Infinix hot 50 mana,1,2026-02-27T03:35:24Z
15,@kucingliar7,baru denger kabar bahwa bulan april nanti semua elektronik bakal naik karena...,0,2026-02-27T01:18:18Z
16,@siriusoct3912,"Kak cobain dong pake hpnya agak lama, karena banyak yg blg infinix mmg bagu...",1,2026-02-26T06:56:53Z
17,@wishmeluck2806,techno camoon 40 pro digoreeeng bgt harganya wkwkwk,1,2026-02-26T04:22:58Z
18,@RakafebrianKadang,Bang coba bandingin realmi GT 7 5G sama xiomi 15T pro,0,2026-02-25T14:52:48Z
19,@Shinfj,Nyari infinix dimana woy?😢😭,0,2026-02-25T12:58:07Z

In [153]:
df_yt.shape

(2725, 6)

In [154]:
df_gd.shape

(5067, 4)

In [155]:
print("Kolom df_yt :", df_yt.columns.tolist())
print("Kolom df_gd :", df_gd.columns.tolist())

Kolom df_yt : ['Channel_Sumber', 'Username', 'Komentar', 'Like_Count', 'Tanggal', 'Tipe_Komentar']
Kolom df_gd : ['Author', 'Comment', 'Likes', 'Time']

In [156]:
# Rename kolom df_yt agar sama dengan df_gd
df_yt = df_yt.rename(columns={
    "Username"   : "Author",
    "Komentar"   : "Comment",
    "Like_Count" : "Likes",
    "Tanggal"    : "Time"
})

# df_gd belum punya kolom ini → tambahkan
df_gd["Channel_Sumber"] = "Gadgetin"
df_gd["Tipe_Komentar"]  = "Utama"

# Verifikasi
print("Kolom df_yt :", df_yt.columns.tolist())
print("Kolom df_gd :", df_gd.columns.tolist())

Kolom df_yt : ['Channel_Sumber', 'Author', 'Comment', 'Likes', 'Time', 'Tipe_Komentar']
Kolom df_gd : ['Author', 'Comment', 'Likes', 'Time', 'Channel_Sumber', 'Tipe_Komentar']

## Gabungkan Dataset

In [157]:
df_gabung = pd.concat([df_yt, df_gd], ignore_index=True)

print(f"df_yt    : {len(df_yt):,} baris")
print(f"df_gd    : {len(df_gd):,} baris")
print(f"Total    : {len(df_gabung):,} baris")
print(f"Kolom    : {df_gabung.columns.tolist()}")
print()
df_gabung.head(20)

df_yt    : 2,725 baris
df_gd    : 5,067 baris
Total    : 7,792 baris
Kolom    : ['Channel_Sumber', 'Author', 'Comment', 'Likes', 'Time', 'Tipe_Komentar']

,Channel_Sumber,Author,Comment,Likes,Time,Tipe_Komentar
0,Jagat Review,@CheverrlynAdyba,"Untuk link pembelian chamon 40 pro 5g kok gk ada bang,",0,2026-03-21T13:04:52Z,Utama
1,Jagat Review,@caesarrizkie9742,"Ngomongin Rog kah ?, kameranya makin menurun, soalnya saya jg dulu liat revi...",0,2026-03-17T20:41:02Z,Utama
2,Jagat Review,@adealfian664,Sebagai user Samsung. One UI itu UI paling enak. UI yang &quot;apa lu mau gu...,0,2026-03-13T23:27:54Z,Utama
3,Jagat Review,@RsyatLyioz,"Tecno pova 7 ultra 5g ,bg",0,2026-03-12T20:11:30Z,Utama
4,Jagat Review,@CitraUtut,bang tolong buatin dong rekomendasi buat lebaran 2026,2,2026-03-02T23:12:23Z,Utama
5,Jagat Review,@KellenArgos-q1f9m,"Gue dapet Infinix gt30 pro 12/512 di harga 3,7 juta, baru tau dari sini kala...",0,2026-03-01T00:48:32Z,Utama
6,Jagat Review,@rifqifadilla6877,Beli toko apa bg,0,2026-03-02T16:50:28Z,Reply
7,Jagat Review,@RahmatRamadhan-e6k,Kalo Samsung s24fe5g aman kh beli taun 2026,0,2026-02-28T15:16:53Z,Utama
8,Jagat Review,@mailnasrunyuiik4983,"bingung gua di seri 3-5 juta ini pada bagus bagus, gua mau beli hp buat leba...",0,2026-02-28T06:41:12Z,Utama
9,Jagat Review,@dengamil2908,kalo camera mending camon tapi kalo untuk ke game mending gt,0,2026-02-28T09:12:22Z,Reply
10,Jagat Review,@RDWNSahabat-Quran,"Bahas samsung galaxy seri M, Gak kalah mantap, gw user M34 dh 2 tahun lebih,...",0,2026-02-26T01:00:12Z,Utama
11,Jagat Review,@rarabatara,"Redmi note 15 5G, ultrawide termurah dengan chipset 5G",0,2026-02-22T02:54:42Z,Utama
12,Jagat Review,@RallyFury-i5k5p,Nah. Kalo dari segi kamera saja. Foto video. Lebih menang Samsung a26 apa a3...,0,2026-02-21T17:13:30Z,Utama
13,Jagat Review,@KatalisOpsianal,Lah hp gw lemot tapi panas gimana tuh😂😂😂 waktunya ganti kali ya udah 5th pak...,0,2026-02-20T20:51:25Z,Utama
14,Jagat Review,@mandra213,kira2 moto g57/67 power bisa masuk ga ya? atau emg ga terpilih aja? wkwk,0,2026-02-17T02:28:54Z,Utama
15,Jagat Review,@zall1150,"<a href=""https://www.youtube.com/watch?v=YuU7NopgJXY&amp;t=793"">13:13</a> r...",0,2026-02-16T01:09:48Z,Utama
16,Jagat Review,@alwafaathea,Di masa depan mending lebih pentingin buat kembangin pendingin mesin dah sup...,1,2026-02-14T08:35:46Z,Utama
17,Jagat Review,@God.SP3ed,"Om Ded, Om Chris dan warga JR semua, info dong dari hp yg disebutkan disini ...",0,2026-02-10T00:57:53Z,Utama
18,Jagat Review,@elvanwijaya3501,"<a href=""https://www.youtube.com/watch?v=YuU7NopgJXY&amp;t=700"">11:40</a> po...",0,2026-02-09T17:03:43Z,Utama
19,Jagat Review,@SuperRossonere,iqoo Z10 pake layar P Oled atau amoled sih???,0,2026-02-07T16:43:22Z,Utama

### Mengecek Missing Value

In [158]:
df_gabung.isnull().sum()

Channel_Sumber    0
Author            0
Comment           0
Likes             0
Time              0
Tipe_Komentar     0
dtype: int64

In [159]:
print(f"Total duplikat : {df_gabung.duplicated().sum()}")

Total duplikat : 28

In [160]:
print()
print("Distribusi channel:")
df_gabung["Channel_Sumber"].value_counts()

Distribusi channel:

Channel_Sumber
Gadgetin         5067
Jagat Review     1463
Pixa Focus ID     903
DKID Media        359
Name: count, dtype: int64

### Menghapus Duplikat

In [161]:
sebelum = len(df_gabung)

df_gabung = df_gabung.drop_duplicates(subset=["Author", "Comment", "Time"], keep="first")

sesudah = len(df_gabung)
print(f"Sebelum : {sebelum:,} baris")
print(f"Dihapus : {sebelum - sesudah} baris")
print(f"Sesudah : {sesudah:,} baris")

Sebelum : 7,792 baris
Dihapus : 28 baris
Sesudah : 7,764 baris

### Cek & Hapus Missing Value

In [162]:
print("Missing sebelum:")
print(df_gabung.isnull().sum())

# Hapus baris yang kolom Comment kosong
df_gabung = df_gabung.dropna(subset=["Comment"])
df_gabung = df_gabung[df_gabung["Comment"].str.strip() != ""]

print(f"Missing sesudah:")
print(df_gabung.isnull().sum())
print(f"Total baris : {len(df_gabung):,}")

Missing sebelum:
Channel_Sumber    0
Author            0
Comment           0
Likes             0
Time              0
Tipe_Komentar     0
dtype: int64
Missing sesudah:
Channel_Sumber    0
Author            0
Comment           0
Likes             0
Time              0
Tipe_Komentar     0
dtype: int64
Total baris : 7,764

### Bersihkan Teks Komentar

In [163]:
def bersihkan_teks(teks):
    if pd.isna(teks):
        return ""
    teks = str(teks)

    teks = html.unescape(teks)                          # decode &amp; dll
    teks = teks.encode('ascii', 'ignore').decode('ascii') # hapus emoji & non-ASCII
    teks = re.sub(r'<br\s*/?>', ' ', teks)              # <br> → spasi
    teks = re.sub(r'<[^>]+>', '', teks)                 # hapus tag HTML
    teks = re.sub(r'http\S+|www\.\S+', '', teks)        # hapus URL
    teks = re.sub(r'@\w+', '', teks)                    # hapus mention
    teks = re.sub(r'#\w+', '', teks)                    # hapus hashtag
    teks = re.sub(r'\b\d+\b', '', teks)                 # hapus angka murni
    teks = re.sub(r'(.)\1{2,}', r'\1\1', teks)          # "bagussss" → "baguss"
    teks = re.sub(r'[!?.]{2,}', '.', teks)              # "!!!" → "."
    teks = re.sub(r'[^\w\s.,!?]', ' ', teks)            # hapus karakter spesial sisa
    teks = re.sub(r'\s+', ' ', teks).strip()            # rapikan spasi
    teks = teks.lower()                                  # huruf kecil semua

    return teks

df_clean = df_gabung.copy()
df_clean["Comment_Raw"] = df_clean["Comment"].copy()
df_clean["Comment_Clean"] = df_clean["Comment"].apply(bersihkan_teks)

df_clean = df_clean[
    df_clean["Comment_Clean"].str.strip() != ""
]

sebelum = len(df_clean)

df_clean = df_clean.drop_duplicates(
    subset=["Author","Comment_Clean","Time"],
    keep="first"
)

sesudah = len(df_clean)

print(f"✅ Cleaning selesai | Sebelum: {sebelum:,} | Dihapus: {sebelum-sesudah:,} | Sisa: {sesudah:,}")

for i, row in df_clean[["Comment_Raw","Comment_Clean"]].head(5).iterrows():
    print(
        f"{i+1}. "
        f"{row['Comment_Raw'][:70]} "
        f"→ {row['Comment_Clean'][:70]}"
    )

✅ Cleaning selesai | Sebelum: 7,695 | Dihapus: 0 | Sisa: 7,695
1. Untuk link pembelian chamon 40 pro 5g kok gk ada bang, → untuk link pembelian chamon pro 5g kok gk ada bang,
2. Ngomongin Rog kah ?, kameranya makin menurun, soalnya saya jg dulu lia → ngomongin rog kah ?, kameranya makin menurun, soalnya saya jg dulu lia
3. Sebagai user Samsung. One UI itu UI paling enak. UI yang &quot;apa lu  → sebagai user samsung. one ui itu ui paling enak. ui yang apa lu mau gu
4. Tecno pova 7 ultra 5g ,bg → tecno pova ultra 5g ,bg
5. bang tolong buatin dong rekomendasi buat lebaran 2026 → bang tolong buatin dong rekomendasi buat lebaran

### Normalisasi Kolom Time

In [164]:
df_clean['Time'] = pd.to_datetime(df_clean['Time'], utc=True, errors='coerce')

# Tambah kolom turunan dari tanggal
df_clean['Tahun'] = df_clean['Time'].dt.year
df_clean['Bulan'] = df_clean['Time'].dt.month
df_clean['Hari']  = df_clean['Time'].dt.day_name()   # Senin, Selasa, dll
df_clean['Jam']   = df_clean['Time'].dt.hour

print("✅ Kolom Time berhasil dikonversi")
print(f"   Rentang: {df_clean['Time'].min()} s/d {df_clean['Time'].max()}")

✅ Kolom Time berhasil dikonversi
   Rentang: 2025-07-26 11:04:00+00:00 s/d 2026-03-28 07:14:54+00:00

### Normalisasi Kolom Likes

In [165]:
df_clean['Likes'] = pd.to_numeric(df_clean['Likes'], errors='coerce').fillna(0).astype(int)

print("✅ Kolom Likes berhasil dinormalisasi")

✅ Kolom Likes berhasil dinormalisasi

### Tambah Fitur Panjang Teks

In [166]:
df_clean['Panjang_Karakter'] = df_clean['Comment_Clean'].str.len()
df_clean['Jumlah_Kata']      = df_clean['Comment_Clean'].str.split().str.len()

print("✅ Kolom fitur teks ditambahkan")
print(f"   Rata-rata panjang komentar : {df_clean['Panjang_Karakter'].mean():.0f} karakter")
print(f"   Rata-rata jumlah kata      : {df_clean['Jumlah_Kata'].mean():.0f} kata")

✅ Kolom fitur teks ditambahkan
   Rata-rata panjang komentar : 71 karakter
   Rata-rata jumlah kata      : 13 kata

In [167]:
df_clean[['Time','Tahun','Bulan','Jam','Likes',
          'Panjang_Karakter','Jumlah_Kata']].head(3)

,Time,Tahun,Bulan,Jam,Likes,Panjang_Karakter,Jumlah_Kata
0,2026-03-21 13:04:52+00:00,2026,3,13,0,51,10
1,2026-03-17 20:41:02+00:00,2026,3,20,0,151,24
2,2026-03-13 23:27:54+00:00,2026,3,23,0,603,116

In [168]:
sebelum = len(df_clean)
df_clean = df_clean[df_clean['Jumlah_Kata'] >= 2]   # minimal 2 kata
sesudah  = len(df_clean)

print(f"✅ Filter komentar terlalu pendek:")
print(f"   Dihapus : {sebelum - sesudah} baris (komentar < 2 kata)")
print(f"   Sisa    : {sesudah:,} baris")

✅ Filter komentar terlalu pendek:
   Dihapus : 283 baris (komentar < 2 kata)
   Sisa    : 7,412 baris

In [169]:
print("\n" + "="*50)
print("   RINGKASAN DATA BERSIH")
print("="*50)
print(f"  Total baris    : {len(df_clean):,}")
print(f"  Missing Value  : {df_clean.isnull().sum().sum()} (total semua kolom)")
print(f"  Duplikat       : {df_clean.duplicated().sum()}")
print()
print("  Distribusi Channel:")
for ch, cnt in df_clean['Channel_Sumber'].value_counts().items():
    pct = cnt / len(df_clean) * 100
    print(f"    {ch:20s}: {cnt:,} ({pct:.1f}%)")
print("="*50)

==================================================
   RINGKASAN DATA BERSIH
==================================================
  Total baris    : 7,412
  Missing Value  : 0 (total semua kolom)
  Duplikat       : 0

  Distribusi Channel:
    Gadgetin            : 4,808 (64.9%)
    Jagat Review        : 1,410 (19.0%)
    Pixa Focus ID       : 847 (11.4%)
    DKID Media          : 347 (4.7%)
==================================================

### Normalisasi Kata Tidak Baku

In [181]:
!pip install -q PySastrawi

kamus_alay = {
    # Negasi
    "gak":"tidak","ga":"tidak","gk":"tidak","ngga":"tidak",
    "nggak":"tidak","ngak":"tidak","enggak":"tidak","tak":"tidak",

    # Kata ganti & sapaan
    "gw":"saya","gue":"saya","gua":"saya","aku":"saya",
    "lo":"kamu","lu":"kamu","elo":"kamu",
    "dy":"dia","doi":"dia","mrk":"mereka",
    "bg":"bang","bng":"bang","kak":"kakak","mas":"mas",
    "bro":"teman","sis":"teman","gan":"teman","sob":"teman",
    "min":"admin","om":"paman",

    # Kata tanya & penghubung
    "gimana":"bagaimana","gmn":"bagaimana","gmana":"bagaimana",
    "kenapa":"mengapa","knp":"mengapa","emng":"memang",
    "emang":"memang","yang":"yang","yg":"yang",
    "dgn":"dengan","dg":"dengan","sama":"dengan",
    "krn":"karena","karna":"karena","soalnya":"karena",
    "tp":"tapi","tpi":"tapi","tetapi":"tapi",
    "klo":"kalau","kl":"kalau","kalo":"kalau",
    "kah":"kah","kh":"kah",

    # Waktu & kondisi
    "udah":"sudah","udh":"sudah","sdh":"sudah",
    "blm":"belum","belom":"belum",
    "msh":"masih","msih":"masih",
    "lg":"lagi","lgi":"lagi",
    "jg":"juga","jga":"juga",
    "aja":"saja","doang":"saja",
    "lbh":"lebih","mending":"lebih baik","mendingan":"lebih baik",
    "hrs":"harus","hrus":"harus",
    "bgt":"banget","bngt":"banget",
    "bnr":"benar","bnr":"benar","bener":"benar",
    "emg":"memang","emang":"memang",

    # Angka dalam kata
    "kira2":"kira-kira","cepet2":"cepat-cepat",
    "pinter2":"pintar-pintar","baik2":"baik-baik",
    "lama2":"lama-lama","makin2":"makin-makin",

    # Kata benda umum
    "hp":"handphone","hape":"handphone","ht":"handphone",
    "spek":"spesifikasi","spec":"spesifikasi","specs":"spesifikasi",
    "merk":"merek","hrg":"harga","hrgnya":"harganya",
    "beli":"beli","bli":"beli",
    "toko":"toko","olshop":"toko online",
    "taun":"tahun","thn":"tahun","bulan":"bulan","bln":"bulan",

    # Kata sifat
    "bagus":"bagus","bgus":"bagus","bguss":"bagus",
    "jelek":"buruk","ancur":"buruk","parah":"buruk",
    "keren":"bagus","mantap":"bagus","mantul":"bagus",
    "murah":"murah","mrah":"murah",
    "mahal":"mahal","mhal":"mahal",
    "lemot":"lambat","lelet":"lambat",
    "cepet":"cepat","cpet":"cepat",
    "panas":"panas","ngelag":"lag",

    # Kata kerja
    "pake":"pakai","pke":"pakai","pk":"pakai",
    "dapet":"dapat","dpet":"dapat",
    "bisa":"bisa","bs":"bisa","bsa":"bisa",
    "mau":"mau","mo":"mau",
    "nonton":"menonton","liat":"melihat","lht":"melihat",
    "beli":"membeli","bli":"membeli",

    # Singkatan teknologi
    "5g":"5g","4g":"4g","ram":"ram","rom":"rom",
    "baterai":"baterai","batre":"baterai","batrai":"baterai",
    "charger":"pengisi daya","cas":"pengisi daya",
    "kamera":"kamera","cam":"kamera",

    # Noise / tawa / ekspresi (dihapus)
    "wkwk":"","wkwkwk":"","wkwkwkwk":"",
    "haha":"","hehe":"","hihi":"","huhu":"",
    "xixi":"","kwkwk":"","wkkwk":"",
    "lol":"","lmao":"","hahaha":"",
}

In [182]:
from nlp_id.lemmatizer import Lemmatizer
import re

lemmatizer = Lemmatizer()

def normalisasi(teks):

    if pd.isna(teks):
        return ""

    teks = str(teks).lower()

    # angka kata
    teks = re.sub(
        r'(\w+)2\b',
        r'\1-\1',
        teks
    )

    # pakai kamus alay
    teks = " ".join(
        kamus_alay.get(kata, kata)
        for kata in teks.split()
    )

    # lemmatizer otomatis
    teks = lemmatizer.lemmatize(teks)

    # hapus kosong
    teks = " ".join(
        k for k in teks.split()
        if k.strip()
    )

    return teks

In [183]:
df_clean["Comment_Norm"] = (
    df_clean["Comment_Clean"]
    .apply(normalisasi)
)

print("✅ Normalisasi selesai")

✅ Normalisasi selesai

In [184]:
df_clean[
    [
        "Comment_Clean",
        "Comment_Norm"
    ]
].sample(10, random_state=42)

,Comment_Clean,Comment_Norm
250,sharp aquos sense,sharp aquos sense
109,tp3ognyari batre iqoo,tp3ognyari baterai iqoo
5056,"saya masih pakai hp vivo y20i ram ,sudah kali ganti lcd sekali ganti baterai...",saya masih pakai handphone vivo y20i ram sudah kali ganti lcd sekali ganti b...
191,tecno camon jt lu asbun ye,tecno camon jt kamu asbun ye
1599,p4o iya bang juga penasaran ingin beli juga,p4o iya bang juga penasaran ingin beli juga
2266,"sehat selalu bang, jgn lupa minum rempah2 bang olahraga",sehat selalu bang jgn lupa minum rempah bang olahraga
5049,infinix hot 4g sekarang beli dimana ya,infinix hot 4g sekarang beli mana ya
2660,"mantap bang, udah kasih like hype",bagus bang sudah kasih like hype
1636,"masih pake infinix hot 4g dpt harga , , blm tergantikan",masih pakai infinix hot 4g dpt harga belum ganti
1704,serius bang eis itu bisa di tambahkan?,serius bang eis itu bisa di tambah

In [173]:
hari_map = {
    "Monday":"Senin",
    "Tuesday":"Selasa",
    "Wednesday":"Rabu",
    "Thursday":"Kamis",
    "Friday":"Jumat",
    "Saturday":"Sabtu",
    "Sunday":"Minggu"
}

df_clean["Hari"] = (
    df_clean["Hari"]
    .map(hari_map)
)

## Tokenisasi

In [174]:
df_clean['Tokens'] = df_clean['Comment_Norm'].str.split()

print("✅ Tokenisasi selesai")
print(f"   Contoh  : {df_clean['Tokens'].iloc[2][:8]}")

✅ Tokenisasi selesai
   Contoh  : ['bagai', 'user', 'samsung', 'one', 'ui', 'itu', 'ui', 'paling']

## Hapus Stopword

In [175]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords', quiet=True)

# Gabung stopword NLTK + tambahan manual bahasa Indonesia
stop_id = set(stopwords.words('indonesian'))
stop_tambahan = {
    'nya', 'yg', 'dg', 'dgn', 'sy', 'gw', 'gue', 'lo', 'lu',
    'bang', 'kak', 'mas', 'pak', 'bu', 'bro', 'sis', 'gan',
    'min', 'min', 'ka', 'bg', 'om', 'teh', 'sob',
    'nih', 'tuh', 'deh', 'dong', 'sih', 'lah', 'kan',
    'ah', 'oh', 'oo', 'oo', 'hm', 'eh'
}
stop_all = stop_id.union(stop_tambahan)

def hapus_stopword(tokens):
    return [kata for kata in tokens if kata not in stop_all]

df_clean['Tokens_Stop'] = df_clean['Tokens'].apply(hapus_stopword)

print("✅ Stopword dihapus")
print(f"   Contoh sebelum : {df_clean['Tokens'].iloc[2][:8]}")
print(f"   Contoh sesudah : {df_clean['Tokens_Stop'].iloc[2][:8]}")

✅ Stopword dihapus
   Contoh sebelum : ['bagai', 'user', 'samsung', 'one', 'ui', 'itu', 'ui', 'paling']
   Contoh sesudah : ['user', 'samsung', 'one', 'ui', 'ui', 'enak', 'ui', 'ui']

## Stemming

In [176]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(tokens):
    return [stemmer.stem(kata) for kata in tokens]

# ⚠️ Proses ini lambat karena 7.000+ baris — tunggu 2-5 menit
print("⏳ Stemming sedang berjalan, harap tunggu...")
df_clean['Tokens_Stem'] = df_clean['Tokens_Stop'].apply(stemming)

# Gabung kembali jadi string (untuk analisis sentimen lexicon)
df_clean['Comment_Final'] = df_clean['Tokens_Stem'].apply(lambda x: ' '.join(x))

print("✅ Stemming selesai!")
print(f"Contoh:")
for i, row in df_clean[['Comment_Clean','Comment_Final']].head(3).iterrows():
    print(f"  AWAL  : {row['Comment_Clean'][:80]}")
    print(f"  FINAL : {row['Comment_Final'][:80]}")
    print()

⏳ Stemming sedang berjalan, harap tunggu...
✅ Stemming selesai!
Contoh:
  AWAL  : untuk link pembelian chamon pro 5g kok gk ada bang,
  FINAL : link beli chamon pro 5g

  AWAL  : ngomongin rog kah ?, kameranya makin menurun, soalnya saya jg dulu liat review c
  FINAL : ngomongin rog kah kamera turun lihat review camera rog jagat pesona handphone ga

  AWAL  : sebagai user samsung. one ui itu ui paling enak. ui yang apa lu mau gua bisa ui
  FINAL : user samsung one ui ui enak ui ui if you can think it it can do it nyari foto sp

In [177]:
df_clean[
    [
        "Comment_Raw",
        "Comment_Clean",
        "Comment_Norm",
        "Comment_Final"
    ]
].sample(10)

,Comment_Raw,Comment_Clean,Comment_Norm,Comment_Final
4788,Poco F7 di Xiaomi store harganya 5.799.000 (skrng ini),poco f7 di xiaomi store harganya . skrng ini,poco f7 di xiaomi store harga skrng ini,poco f7 xiaomi store harga skrng
5870,bismillah semoga gatgetin selalu maju jaya dan dimudahkan segala urusan,bismillah semoga gatgetin selalu maju jaya dan dimudahkan segala urusan,bismillah moga gatgetin selalu maju jaya dan mudah segala urus,bismillah moga gatgetin maju jaya mudah urus
1230,Ini yg gw tunggu2,ini yg gw tunggu2,ini yang saya tunggu,tunggu
2450,Moto edge 60 fusion,moto edge fusion,moto edge fusion,moto edge fusion
3089,Yang make Infinix hot 50 cungg 😂,yang make infinix hot cungg,yang make infinix hot cungg,make infinix hot cungg
4027,Saya pake pendahulunya vivo X100 aja dah gila mantep bener. Sebagai pertama ...,saya pake pendahulunya vivo x100 aja dah gila mantep bener. sebagai pertama ...,saya pakai dahulu vivo x100 saja dah gila mantep bener bagai pertama kali pa...,pakai vivo x100 dah gila mantep bener kali pakai flagship
7444,Konten yang paling ditunggu!!!,konten yang paling ditunggu.,konten yang paling tunggu,konten tunggu
5494,Adik saya mau beli hp baru dlm kepalanya cuma dua samsung a56 &amp; oppo ren...,adik saya mau beli hp baru dlm kepalanya cuma dua samsung a56 oppo reno 14f....,adik saya mau beli handphone baru dlm kepala cuma dua samsung a56 oppo reno ...,adik beli handphone dlm kepala samsung a56 oppo reno 14f limit budget juta d...
6655,Akhirnya hp yang gua beli jadi juara Infinix hot 60 pro gua dapet di harga 1...,"akhirnya hp yang gua beli jadi juara infinix hot pro gua dapet di harga , juta",akhir handphone yang saya beli jadi juara infinix hot pro saya dapat di harg...,handphone beli juara infinix hot pro harga juta
1572,​@adityatav1yah masih mempertanyakan sepuhnya hp..,masih mempertanyakan sepuhnya hp.,masih tanya sepuh hp,sepuh hp

## Cek Kualitas

In [178]:
# Hapus yang jadi kosong setelah stemming
sebelum = len(df_clean)
df_clean = df_clean[df_clean['Comment_Final'].str.strip() != '']
df_clean = df_clean[df_clean['Tokens_Stem'].apply(len) >= 2]
sesudah  = len(df_clean)

print("=" * 50)
print("     CEK KUALITAS AKHIR LENGKAP")
print("=" * 50)
print(f"  Baris sebelum filter akhir : {sebelum:,}")
print(f"  Baris terhapus             : {sebelum - sesudah}")
print(f"  Baris final                : {sesudah:,}")
print(f"  Missing Value              : {df_clean.isnull().sum().sum()}")

kolom_cek = ['Channel_Sumber', 'Author', 'Comment_Final', 'Time']
print(f"  Duplikat                   : {df_clean.duplicated(subset=kolom_cek).sum()}")

print()
print("  Rata-rata token per komentar:")
print(f"    Sebelum stopword : {df_clean['Tokens'].apply(len).mean():.1f} kata")
print(f"    Setelah stopword : {df_clean['Tokens_Stop'].apply(len).mean():.1f} kata")
print(f"    Setelah stemming : {df_clean['Tokens_Stem'].apply(len).mean():.1f} kata")
print()
print("  Distribusi Channel:")
for ch, cnt in df_clean['Channel_Sumber'].value_counts().items():
    print(f"    {ch:20s}: {cnt:,} ({cnt/len(df_clean)*100:.1f}%)")
print("=" * 50)

==================================================
     CEK KUALITAS AKHIR LENGKAP
==================================================
  Baris sebelum filter akhir : 7,412
  Baris terhapus             : 378
  Baris final                : 7,034
  Missing Value              : 0
  Duplikat                   : 0

  Rata-rata token per komentar:
    Sebelum stopword : 13.4 kata
    Setelah stopword : 8.1 kata
    Setelah stemming : 8.1 kata

  Distribusi Channel:
    Gadgetin            : 4,566 (64.9%)
    Jagat Review        : 1,344 (19.1%)
    Pixa Focus ID       : 801 (11.4%)
    DKID Media          : 323 (4.6%)
==================================================

In [179]:
# Simpan file final
df_clean.to_csv('Youtubeclean_final.csv', index=False, encoding='utf-8-sig')

df_sentimen = df_clean[['Channel_Sumber','Author','Comment_Final',
                         'Likes','Time','Tipe_Komentar']].copy()
df_sentimen.to_csv('Youtube_sentiment.csv', index=False, encoding='utf-8-sig')

print("✅ File tersimpan:")
print("   Youtube clean_final.csv   → lengkap semua kolom")
print("   Youtube_sentiment.csv → siap analisis sentimen")

✅ File tersimpan:
   Youtube clean_final.csv   → lengkap semua kolom
   Youtube_sentiment.csv → siap analisis sentimen

In [180]:
df_clean.head()

,Channel_Sumber,Author,Comment,Likes,Time,Tipe_Komentar,Comment_Raw,Comment_Clean,Tahun,Bulan,Hari,Jam,Panjang_Karakter,Jumlah_Kata,Comment_Norm,Tokens,Tokens_Stop,Tokens_Stem,Comment_Final
0,Jagat Review,@CheverrlynAdyba,"Untuk link pembelian chamon 40 pro 5g kok gk ada bang,",0,2026-03-21 13:04:52+00:00,Utama,"Untuk link pembelian chamon 40 pro 5g kok gk ada bang,","untuk link pembelian chamon pro 5g kok gk ada bang,",2026,3,Sabtu,13,51,10,untuk link beli chamon pro 5g kok tidak ada bang,"[untuk, link, beli, chamon, pro, 5g, kok, tidak, ada, bang]","[link, beli, chamon, pro, 5g]","[link, beli, chamon, pro, 5g]",link beli chamon pro 5g
1,Jagat Review,@caesarrizkie9742,"Ngomongin Rog kah ?, kameranya makin menurun, soalnya saya jg dulu liat revi...",0,2026-03-17 20:41:02+00:00,Utama,"Ngomongin Rog kah ?, kameranya makin menurun, soalnya saya jg dulu liat revi...","ngomongin rog kah ?, kameranya makin menurun, soalnya saya jg dulu liat revi...",2026,3,Selasa,20,151,24,ngomongin rog kah kamera makin turun karena saya juga dulu lihat review came...,"[ngomongin, rog, kah, kamera, makin, turun, karena, saya, juga, dulu, lihat,...","[ngomongin, rog, kah, kamera, turun, lihat, review, camera, rog, jagat, peso...","[ngomongin, rog, kah, kamera, turun, lihat, review, camera, rog, jagat, peso...",ngomongin rog kah kamera turun lihat review camera rog jagat pesona handphon...
2,Jagat Review,@adealfian664,Sebagai user Samsung. One UI itu UI paling enak. UI yang &quot;apa lu mau gu...,0,2026-03-13 23:27:54+00:00,Utama,Sebagai user Samsung. One UI itu UI paling enak. UI yang &quot;apa lu mau gu...,sebagai user samsung. one ui itu ui paling enak. ui yang apa lu mau gua bisa...,2026,3,Jumat,23,603,116,bagai user samsung one ui itu ui paling enak ui yang apa kamu mau saya bisa ...,"[bagai, user, samsung, one, ui, itu, ui, paling, enak, ui, yang, apa, kamu, ...","[user, samsung, one, ui, ui, enak, ui, ui, if, you, can, think, it, it, can,...","[user, samsung, one, ui, ui, enak, ui, ui, if, you, can, think, it, it, can,...",user samsung one ui ui enak ui ui if you can think it it can do it nyari fot...
3,Jagat Review,@RsyatLyioz,"Tecno pova 7 ultra 5g ,bg",0,2026-03-12 20:11:30+00:00,Utama,"Tecno pova 7 ultra 5g ,bg","tecno pova ultra 5g ,bg",2026,3,Kamis,20,23,5,tecno pova ultra 5g bg,"[tecno, pova, ultra, 5g, bg]","[tecno, pova, ultra, 5g]","[tecno, pova, ultra, 5g]",tecno pova ultra 5g
4,Jagat Review,@CitraUtut,bang tolong buatin dong rekomendasi buat lebaran 2026,2,2026-03-02 23:12:23+00:00,Utama,bang tolong buatin dong rekomendasi buat lebaran 2026,bang tolong buatin dong rekomendasi buat lebaran,2026,3,Senin,23,48,7,bang tolong buatin dong rekomendasi buat lebaran,"[bang, tolong, buatin, dong, rekomendasi, buat, lebaran]","[tolong, buatin, rekomendasi, lebaran]","[tolong, buatin, rekomendasi, lebaran]",tolong buatin rekomendasi lebaran